apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo
        args: ["-text=Félicitations ! Ton trafic passe par Kong sur Scaleway."]
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
  namespace: kong
spec:
  selector:
    app: echo-server
  ports:
    - port: 80
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong # Indispensable pour que Kong capte la route
spec:
  rules:
  - http:
      paths:
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: echo-service
            port:
              number: 80