apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-gateway
  namespace: argocd
spec:
  project: default
  source:
    # On pointe vers le dépôt officiel pour le code de Kong...
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.36.0
    helm:
      # ...MAIS on utilise ton fichier values.yaml sur TON GitHub pour les réglages
      valueFiles:
        - https://raw.githubusercontent.com/smateve/kong-scaleway-test/main/infrastructure/kong/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true